server:
    port: 8080

spring:
    application:
        name: trans
    profiles:
        active: local

logging:
    level:
        com.hsbc.trans: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

snowflake:
    datacenter-id: 1  # 数据中心ID（0-31）
    worker-id: 1      # 工作机器ID（0-31）